name: Golang CI

on: 
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  go-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Adjust to the version of Go you're using

      - name: Run Go build
        run: go build -o main .
        working-directory: ./  # If Go code is in the root directory

      - name: Display Go build status
        run: echo "🍏 Go build job status is ${{ job.status }}."
